<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the MIT License along with
//  the library. If not, see <http://opensource.org/licenses/MIT>.
//
//----------------------------------------------------------------------

namespace Linode\Linode;

use Linode\BaseLinodeApi;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class JobApi extends BaseLinodeApi
{
    /**
     * @param int  $LinodeID    [required]
     * @param int  $JobID       [optional] Limits the list to the specified JobID
     * @param bool $pendingOnly [optional]
     *
     * @return array
     */
    public function getList($LinodeID, $JobID = null, $pendingOnly = null)
    {
        return $this->call('linode.job.list', array(
            'LinodeID'    => $LinodeID,
            'JobID'       => $JobID,
            'pendingOnly' => $pendingOnly,
        ));
    }
}
