<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the GNU General Public License
//  along with the library. If not, see <http://www.gnu.org/licenses/>.
//
//----------------------------------------------------------------------

namespace Linode\Linode;

use Linode\BaseLinodeApi;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class JobApi extends BaseLinodeApi
{
    /**
     *
     *
     * @param   integer $LinodeID    [required]
     * @param   integer $JobID       [optional] Limits the list to the specified JobID
     * @param   boolean $pendingOnly [optional]
     *
     * @return  array
     */
    public function getList($LinodeID, $JobID = null, $pendingOnly = null)
    {
        return $this->call('linode.job.list', array(
            'LinodeID'    => $LinodeID,
            'JobID'       => $JobID,
            'pendingOnly' => $pendingOnly,
        ));
    }
}
