<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the MIT License along with
//  the library. If not, see <http://opensource.org/licenses/MIT>.
//
//----------------------------------------------------------------------

namespace Linode\Domain;

use Linode\BaseLinodeApi;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class ResourceApi extends BaseLinodeApi
{
    /**
     * Create a domain record.
     *
     * @param int    $DomainID [required]
     * @param string $Type     [required] One of: NS, MX, A, AAAA, CNAME, TXT, or SRV
     * @param string $Name     [optional] The hostname or FQDN.  When Type=MX the subdomain to delegate to the Target MX server.
     * @param string $Target   [optional] When Type=MX the hostname.  When Type=CNAME the target of the alias.  When Type=TXT the value of the record. When Type=A or AAAA the token of '[remote_addr]' will be substituted with the IP address of the request.
     * @param int    $Priority [optional] Priority for MX and SRV records, 0-255
     * @param int    $Weight   [optional]
     * @param int    $Port     [optional]
     * @param string $Protocol [optional] The protocol to append to an SRV record.  Ignored on other record types.
     * @param int    $TTL_sec  [optional] TTL.  Leave as 0 to accept our default.
     *
     * @return array
     */
    public function create($DomainID, $Type, $Name = null, $Target = null, $Priority = null, $Weight = null, $Port = null, $Protocol = null, $TTL_sec = null)
    {
        return $this->call('domain.resource.create', array(
            'DomainID' => $DomainID,
            'Type'     => $Type,
            'Name'     => $Name,
            'Target'   => $Target,
            'Priority' => $Priority,
            'Weight'   => $Weight,
            'Port'     => $Port,
            'Protocol' => $Protocol,
            'TTL_sec'  => $TTL_sec,
        ));
    }

    /**
     * @param int $DomainID   [required]
     * @param int $ResourceID [required]
     *
     * @return array
     */
    public function delete($DomainID, $ResourceID)
    {
        return $this->call('domain.resource.delete', array(
            'DomainID'   => $DomainID,
            'ResourceID' => $ResourceID,
        ));
    }

    /**
     * @param int $DomainID   [required]
     * @param int $ResourceID [optional]
     *
     * @return array
     */
    public function getList($DomainID, $ResourceID = null)
    {
        return $this->call('domain.resource.list', array(
            'DomainID'   => $DomainID,
            'ResourceID' => $ResourceID,
        ));
    }

    /**
     * Update a domain record.
     *
     * @param int    $DomainID   [optional]
     * @param int    $ResourceID [required]
     * @param string $Name       [optional] The hostname or FQDN.  When Type=MX the subdomain to delegate to the Target MX server.
     * @param string $Target     [optional] When Type=MX the hostname.  When Type=CNAME the target of the alias.  When Type=TXT the value of the record. When Type=A or AAAA the token of '[remote_addr]' will be substituted with the IP address of the request.
     * @param int    $Priority   [optional] Priority for MX and SRV records, 0-255
     * @param int    $Weight     [optional]
     * @param int    $Port       [optional]
     * @param string $Protocol   [optional] The protocol to append to an SRV record.  Ignored on other record types.
     * @param int    $TTL_sec    [optional] TTL.  Leave as 0 to accept our default.
     *
     * @return array
     */
    public function update($DomainID = null, $ResourceID, $Name = null, $Target = null, $Priority = null, $Weight = null, $Port = null, $Protocol = null, $TTL_sec = null)
    {
        return $this->call('domain.resource.update', array(
            'DomainID'   => $DomainID,
            'ResourceID' => $ResourceID,
            'Name'       => $Name,
            'Target'     => $Target,
            'Priority'   => $Priority,
            'Weight'     => $Weight,
            'Port'       => $Port,
            'Protocol'   => $Protocol,
            'TTL_sec'    => $TTL_sec,
        ));
    }
}
