<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the GNU General Public License
//  along with the library. If not, see <http://www.gnu.org/licenses/>.
//
//----------------------------------------------------------------------

namespace Linode\NodeBalancer;

use Linode\BaseLinodeApi;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class Node extends BaseLinodeApi
{
    /**
     *
     *
     * @param   string  $Label    [required] This backend Node's label
     * @param   integer $ConfigID [required] The parent ConfigID to attach this Node to
     * @param   string  $Mode     [optional] The connections mode for this node.  One of 'accept', 'reject', or 'drain'
     * @param   integer $Weight   [optional] Load balancing weight, 1-255. Higher means more connections.
     * @param   string  $Address  [required] The address:port combination used to communicate with this Node
     *
     * @return  array
     */
    public function create($Label, $ConfigID, $Mode = null, $Weight = null, $Address = null)
    {
        return $this->call('nodebalancer.node.create', array(
            'Label'    => $Label,
            'ConfigID' => $ConfigID,
            'Mode'     => $Mode,
            'Weight'   => $Weight,
            'Address'  => $Address,
        ));
    }

    /**
     * Deletes a Node from a NodeBalancer Config
     *
     * @param   integer $NodeID [required] The NodeID to delete
     *
     * @return  array
     */
    public function delete($NodeID)
    {
        return $this->call('nodebalancer.node.delete', array(
            'NodeID' => $NodeID,
        ));
    }

    /**
     * Returns a list of Nodes associated with a NodeBalancer Config
     *
     * @param   integer $NodeID   [optional] Limits the list to the specified NodeID
     * @param   integer $ConfigID [required]
     *
     * @return  array
     */
    public function getList($NodeID = null, $ConfigID = null)
    {
        return $this->call('nodebalancer.node.list', array(
            'NodeID'   => $NodeID,
            'ConfigID' => $ConfigID,
        ));
    }

    /**
     * Updates a Node's properties
     *
     * @param   string  $Label   [optional] This backend Node's label
     * @param   integer $NodeID  [required]
     * @param   string  $Mode    [optional] The connections mode for this node.  One of 'accept', 'reject', or 'drain'
     * @param   integer $Weight  [optional] Load balancing weight, 1-255. Higher means more connections.
     * @param   string  $Address [optional] The address:port combination used to communicate with this Node
     *
     * @return  array
     */
    public function update($Label = null, $NodeID = null, $Mode = null, $Weight = null, $Address = null)
    {
        return $this->call('nodebalancer.node.update', array(
            'Label'   => $Label,
            'NodeID'  => $NodeID,
            'Mode'    => $Mode,
            'Weight'  => $Weight,
            'Address' => $Address,
        ));
    }
}
