<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the GNU General Public License
//  along with the library. If not, see <http://www.gnu.org/licenses/>.
//
//----------------------------------------------------------------------

namespace Linode;

use Linode\BaseLinodeApi;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class Domain extends BaseLinodeApi
{
    /**
     * Create a domain record.
     *
     * @param   string  $SOA_Email        [optional] Required when type=master
     * @param   string  $Description      [optional] Currently undisplayed.
     * @param   integer $TTL_sec          [optional]
     * @param   integer $Retry_sec        [optional]
     * @param   integer $Expire_sec       [optional]
     * @param   string  $Domain           [required] The zone's name
     * @param   integer $status           [optional] 0, 1, or 2 (disabled, active, edit mode)
     * @param   string  $Type             [required] master or slave
     * @param   integer $Refresh_sec      [optional]
     * @param   string  $lpm_displayGroup [optional] Display group in the Domain list inside the Linode DNS Manager
     * @param   string  $master_ips       [optional] When type=slave, the zone's master DNS servers list, semicolon separated
     * @param   string  $axfr_ips         [optional] IP addresses allowed to AXFR the entire zone, semicolon separated
     *
     * @return  array
     */
    public function create($SOA_Email = null, $Description = null, $TTL_sec = null, $Retry_sec = null, $Expire_sec = null, $Domain = null, $status = null, $Type = null, $Refresh_sec = null, $lpm_displayGroup = null, $master_ips = null, $axfr_ips = null)
    {
        return $this->call('domain.create', array(
            'SOA_Email'        => $SOA_Email,
            'Description'      => $Description,
            'TTL_sec'          => $TTL_sec,
            'Retry_sec'        => $Retry_sec,
            'Expire_sec'       => $Expire_sec,
            'Domain'           => $Domain,
            'status'           => $status,
            'Type'             => $Type,
            'Refresh_sec'      => $Refresh_sec,
            'lpm_displayGroup' => $lpm_displayGroup,
            'master_ips'       => $master_ips,
            'axfr_ips'         => $axfr_ips,
        ));
    }

    /**
     *
     *
     * @param   integer $DomainID [required]
     *
     * @return  array
     */
    public function delete($DomainID)
    {
        return $this->call('domain.delete', array(
            'DomainID' => $DomainID,
        ));
    }

    /**
     * Lists domains you have access to.
     *
     * @param   integer $DomainID [optional] Limits the list to the specified DomainID
     *
     * @return  array
     */
    public function getList($DomainID = null)
    {
        return $this->call('domain.list', array(
            'DomainID' => $DomainID,
        ));
    }

    /**
     * Update a domain record.
     *
     * @param   integer $DomainID         [required]
     * @param   string  $Description      [optional] Currently undisplayed.
     * @param   integer $Retry_sec        [optional]
     * @param   integer $Expire_sec       [optional]
     * @param   integer $status           [optional] 0, 1, or 2 (disabled, active, edit mode)
     * @param   integer $Refresh_sec      [optional]
     * @param   string  $lpm_displayGroup [optional] Display group in the Domain list inside the Linode DNS Manager
     * @param   string  $master_ips       [optional] When type=slave, the zone's master DNS servers list, semicolon separated
     * @param   string  $SOA_Email        [optional] Required when type=master
     * @param   integer $TTL_sec          [optional]
     * @param   string  $Domain           [optional] The zone's name
     * @param   string  $Type             [optional] master or slave
     * @param   string  $axfr_ips         [optional] IP addresses allowed to AXFR the entire zone, semicolon separated
     *
     * @return  array
     */
    public function update($DomainID, $Description = null, $Retry_sec = null, $Expire_sec = null, $status = null, $Refresh_sec = null, $lpm_displayGroup = null, $master_ips = null, $SOA_Email = null, $TTL_sec = null, $Domain = null, $Type = null, $axfr_ips = null)
    {
        return $this->call('domain.update', array(
            'DomainID'         => $DomainID,
            'Description'      => $Description,
            'Retry_sec'        => $Retry_sec,
            'Expire_sec'       => $Expire_sec,
            'status'           => $status,
            'Refresh_sec'      => $Refresh_sec,
            'lpm_displayGroup' => $lpm_displayGroup,
            'master_ips'       => $master_ips,
            'SOA_Email'        => $SOA_Email,
            'TTL_sec'          => $TTL_sec,
            'Domain'           => $Domain,
            'Type'             => $Type,
            'axfr_ips'         => $axfr_ips,
        ));
    }
}
