<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015-2017 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the MIT License along with
//  the library. If not, see <http://opensource.org/licenses/MIT>.
//
//----------------------------------------------------------------------

namespace Linode;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class ImageApi extends BaseLinodeApi
{
    /**
     * Deletes a gold-master image.
     *
     * @param int $ImageID [required] The ID of the gold-master image to delete
     *
     * @return array
     */
    public function delete($ImageID)
    {
        return $this->call('image.delete', [
            'ImageID' => $ImageID,
        ]);
    }

    /**
     * Lists available gold-master images.
     *
     * @param int $ImageID [optional] Request information for a specific gold-master image
     * @param int $pending [optional] Show images currently being created.
     *
     * @return array
     */
    public function getList($ImageID = null, $pending = null)
    {
        return $this->call('image.list', [
            'ImageID' => $ImageID,
            'pending' => $pending,
        ]);
    }

    /**
     * Update an Image record.
     *
     * @param int    $ImageID     [required] The ID of the Image to modify.
     * @param string $label       [optional] The label of the Image.
     * @param string $description [optional] An optional description of the Image.
     *
     * @return array
     */
    public function update($ImageID, $label = null, $description = null)
    {
        return $this->call('image.update', [
            'ImageID'     => $ImageID,
            'label'       => $label,
            'description' => $description,
        ]);
    }
}
