<?php

//----------------------------------------------------------------------
//
//  Copyright (C) 2015-2017 Artem Rodygin
//
//  This file is part of Linode API Client Library for PHP.
//
//  You should have received a copy of the MIT License along with
//  the library. If not, see <http://opensource.org/licenses/MIT>.
//
//----------------------------------------------------------------------

namespace Linode;

/**
 * This class is autogenerated.
 *
 * @version Linode API v3.3
 */
class VolumeApi extends BaseLinodeApi
{
    /**
     * Creates a new Block Storage Volume. One of DatacenterID or LinodeID is required.
     *
     * @param int    $DatacenterID [optional] Sets the datacenter where the Volume should be provisioned
     * @param string $Label        [required] A unique name for the Volume
     * @param int    $Size         [required] Sets the size of the new Volume in GiB
     * @param int    $LinodeID     [optional] The Linode to attach this Volume to
     *
     * @return array
     */
    public function create($DatacenterID, $Label, $Size, $LinodeID = null)
    {
        return $this->call('volume.create', [
            'DatacenterID' => $DatacenterID,
            'Label'        => $Label,
            'Size'         => $Size,
            'LinodeID'     => $LinodeID,
        ]);
    }

    /**
     * Deletes a Block Storage Volume.
     *
     * @param int $VolumeID [required] The Volume to delete
     *
     * @return array
     */
    public function delete($VolumeID)
    {
        return $this->call('volume.delete', [
            'VolumeID' => $VolumeID,
        ]);
    }

    /**
     * Clones an existing Block Storage Volume.
     *
     * @param int    $CloneFromID [required]
     * @param string $Label       [required] A unique name for the new Volume
     *
     * @return array
     */
    public function duplicate($CloneFromID, $Label)
    {
        return $this->call('volume.clone', [
            'CloneFromID' => $CloneFromID,
            'Label'       => $Label,
        ]);
    }

    /**
     * Returns a list of block storage Volumes.
     *
     * @param int $VolumeID [optional] Limits the list to the specified Volume
     *
     * @return array
     */
    public function getList($VolumeID = null)
    {
        return $this->call('volume.list', [
            'VolumeID' => $VolumeID,
        ]);
    }

    /**
     * Updates a Volume's properties.
     *
     * @param int    $VolumeID [required] The Volume to modify
     * @param string $Label    [optional] A unique name for the Volume
     * @param int    $Size     [optional] Sets the new size of the new Volume in GiB; Volumes can only be made larger
     * @param int    $LinodeID [optional] The Linode to attach this Volume to
     *
     * @return array
     */
    public function update($VolumeID, $Label = null, $Size = null, $LinodeID = null)
    {
        return $this->call('volume.update', [
            'VolumeID' => $VolumeID,
            'Label'    => $Label,
            'Size'     => $Size,
            'LinodeID' => $LinodeID,
        ]);
    }
}
